name: CI
on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"
      - run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Reference
        run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
        id: ref
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: tnttime-${{ steps.ref.outputs.branch }}
          path: build/libs